### PR TITLE
Limit Guardian GitHub comment length

### LINKED ISSUE #238: Guardian fails when trying to create comment for plan that is over 65536 characters
### TL;DR

The GitHub Issues API limits the size of comments to `65536` characters. Guardian needs to truncate the size of a comment to less and add details about viewing the logs for the workflow run.

### Expected behavior

_No response_

### Observed behavior

_No response_

### Environment Details

```markdown
All
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by lock14**
* Ensure Guardian does not exceed GitHub's comment length limit when making comments. If the message exceeds the maximum length, it is truncated and a sentence is added to the end indicating that the full message can be viewed in the workflow logs.

closes #238

### CODE REVIEW

**Review by sethvargo — DISMISSED** [review]

File: pkg/commands/plan/plan_run.go [hunk 1]
```diff
@@ -286,22 +305,22 @@ func (c *PlanRunCommand) updateResultCommentForActions(ctx context.Context, star
...
 		if result.commentDetails != "" {
-			fmt.Fprintf(&comment, "\n\n<details>\n<summary>Details</summary>\n\n```diff\n\n%s\n```\n</details>", result.commentDetails)
+			// Ensure the comment is not over GitHub's limit. We need to account for the surrounding characters we will
+			// be adding in addition to the length of result.commentDetails.
+			fmtString := "\n\n<details>\n<summary>Details</summary>\n\n```diff\n\n%s\n```\n</details>"
+			truncationMsg := []rune("...\n\nMessage has been truncated. See workflow logs to view the full message.")
+			cappedLength := gitHubMaxCommentLength - len(truncationMsg) - len([]rune(comment.String())) - len([]rune(fmtString)) + 2
+			if len([]rune(result.commentDetails)) > cappedLength {
+				runes := []rune(result.commentDetails)[:cappedLength]
+				runes = append(runes, truncationMsg...)
```
Comment (verbanicm) [inline pkg/commands/plan/plan_run.go:315]: Should we move the truncation message outside of the details so its obvious on the comment? Rather than the user having to go the entire way through the output only to realize its truncated?

Comment (lock14) [reply pkg/commands/plan/plan_run.go]: I think that is probably a better user experience. I've moved the truncation message outside the comment details section of the comment.

**Review by verbanicm — APPROVED** [review]
